[build_system]
requires = ["setup_tools"]
build-backend = "setup_tools.build_meta"

[project]
name = "shifting_browser_fingerprints"
version = "0.0.6"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.*"]
